import imgMovie from '../images/movie.png';
export const moviesData = [
    {
        _id: 1,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": true,
    },
    {
        _id: 2,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": false,
    },
    {
        _id: 3,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": true,
    },
    {
        _id: 4,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": false,
    },
    {
        _id: 5,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": true,
    },
    {
        _id: 6,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": false,
    },
    {
        _id: 7,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": true,
    },
    {
        _id: 8,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": false,
    },
    {
        _id: 9,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": true,
    },
    {
        _id: 10,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": false,
    },
    {
        _id: 11,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": true,
    },
    {
        _id: 12,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": false,
    },
]

export const savedMoviesData = [
    {
        _id: 1,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": true,
    },
    {
        _id: 2,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": false,
    },
    {
        _id: 3,
        "title": "В погоне за Бенкси",
        "duration": "27 минут",
        "imgMovie": imgMovie,
        "isSaved": true,
    },
]